export class Events {
    static READY = "READY";
    static CHANNEL_CREATED = "CHANNEL_CREATED";
    static CHANNEL_DELETED = "CHANNEL_DELETED";
    static CHANNEL_UPDATED = "CHANNEL_UPDATED";
    static MESSAGE_SEND = "MESSAGE_SEND";
    static MESSAGE_UPDATED = "MESSAGE_UPDATED";
    static MESSAGE_DELETED = "MESSAGE_DELETED";
    static MESSAGE_REACTION_ADDED = "MESSAGE_REACTION_ADDED";
    static MESSAGE_REACTION_REMOVED = "MESSAGE_REACTION_REMOVED";
    static PRESENCE_UPDATE = "PRESENCE_UPDATE";
    static TEAM_ROLE_CREATED = "TEAM_ROLE_CREATED";
    static TEAM_ROLE_UPDATED = "TEAM_ROLE_UPDATED";
    static TEAM_ROLE_DELETED = "TEAM_ROLE_DELETED";
    static TEAM_UPDATED = "TEAM_UPDATED";
    static TODO_ITEM_CREATED = "TODO_ITEM_CREATED";
    static TODO_ITEM_DELETED = "TODO_ITEM_DELETED";
    static TODO_ITEM_UPDATED = "TODO_ITEM_UPDATED";
    static USER_JOINED_TEAM = "USER_JOINED_TEAM";
    static USER_LEFT_TEAM = "USER_LEFT_TEAM";
    static USER_JOINED_VOICE_CHANNEL = "USER_JOINED_VOICE_CHANNEL";
    static USER_LEFT_VOICE_CHANNEL = "USER_LEFT_VOICE_CHANNEL";
    static USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED";
    static USER_ROLE_ADDED = "USER_ROLE_ADDED";
    static USER_ROLE_REMOVED = "USER_ROLE_REMOVED";
    static USER_UPDATE_VOICE_METADATA = "USER_UPDATE_VOICE_METADATA";
    static BLOG_CREATED = "BLOG_CREATED";
    static BLOG_DELETED = "BLOG_DELETED";
    static CATEGORIES_PRIORITY_UPDATED = "CATEGORIES_PRIORITY_UPDATED";
    static CATEGORY_UPDATED = "CATEGORY_UPDATED";
    static CATEGORY_DELETED = "CATEGORY_DELETED";
    static CATEGORY_CREATED = "CATEGORY_CREATED";
    static CATEGORY_DELTED = "CATEGORY_DELETED";
    static CATEGORY_CREATED = "CATEGORY_CREATED";
    static CHANNELS_PRIORITY_UPDATED = "CHANNELS_PRIORITY_UPDATED";
    static ANNOUNCEMENT_CREATED = "ANNOUNCEMENT_CREATED";
    static ANNOUNCEMENT_DELETED = "ANNOUNCEMENT_DELETED";
    static APPLICATION_CREATED = "APPLICATION_CREATED";
    static APPLICATION_DELETED = "APPLICATION_DELETED";
    static VOICE_CHANNEL_MOVE = "VOICE_CHANNEL_MOVE";
    static ERROR = "ERROR";

    static fromString(eventType) {
        return Events[eventType.toUpperCase()] || null;
    }
}